### ISSUE TITLE
Adding markers with custom icons

### ISSUE THREAD

**Issue by Mahroz** [NGame1/UWPGmaps.SDK#1]
Hi, I was using this NuGet package(great work!), but I was unable to add markers to map with custom icons.  Also I was unable to find any documentation about the UWPGmaps.SDK

**Comment by NGame1** [comment]
Hi and thanks for using our NuGET package. 

[How To Use Google Maps in UWP C#](https://www.codeproject.com/Tips/1233432/Using-Google-maps-API-in-UWP-Csharp)

In this link from CodeProject you can see how to use our SDK and NuGET.
I can remember that I tried MapElements with custom icon before with no issues and also using MapElement without custom icon in my app "WinGo Maps" without any issue. but I will try it once again and let you know.

**Comment by NGame1** [comment]
I tried MapElement with custom icon it worked 
![Result](http://s8.picofile.com/file/8324618000/Untitled.png)

Here's my code

```
var iconfile = await Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///Assets/InAppIcons/GMP.png", UriKind.RelativeOrAbsolute));
Map.MapElements.Add(new MapIcon()
{
        Image = Windows.Storage.Streams.RandomAccessStreamReference.CreateFromFile( iconfile ),
        Location = new Geopoint(new BasicGeoposition() { Latitude = Latitude, Longitude = Longitude }),
        Title = PlaceName
});
```

**Comment by Mahroz** [comment]
Hi, thanks a lot for your help. I'll try that as soon as possible.


Mohammad Mahroz

Mobile : 0092-307-4489564

Email : m.mahroz.52@gmail.com
